import Foundation

enum QuestionBank {

    // Índices según tu app:
    // 0 Geografía
    // 1 Arte y Literatura
    // 2 Historia
    // 3 Entretenimiento (cine, TV, famosos y algo de música pop)
    // 4 Ciencias y Naturaleza
    // 5 Deportes y Pasatiempos

    static func questions(for categoryIndex: Int) -> [Question] {
        switch categoryIndex {
        case 0: return geography
        case 1: return artAndLiterature
        case 2: return history
        case 3: return entertainment
        case 4: return scienceAndNature
        case 5: return sports
        default: return []
        }
    }

    // MARK: - Geografía (0)
    // Mezcla de capitales, países, banderas, lugares y geografía física.
    private static let geography: [Question] = [
        q("¿De qué país es originario el queso brie?",
          correct: "Francia",
          wrong: ["Italia", "Suiza", "Bélgica"]),
        q("¿De qué colores es la bandera de Japón?",
          correct: "Blanca y roja",
          wrong: ["Roja y blanca", "Blanca y azul", "Roja y amarilla"]),
        q("¿Dónde se encuentra el museo de Louvre?",
          correct: "París",
          wrong: ["Lyon", "Marsella", "Burdeos"]),
        q("¿Cuál es la capital de Nigeria?",
          correct: "Abuya",
          wrong: ["Lagos", "Kano", "Abuya es la capital (truco)"]),
        q("¿Cuál es el país más grande del mundo?",
          correct: "Rusia",
          wrong: ["China", "Canadá", "Estados Unidos"]),
        q("¿Cuál es el río más largo del planeta?",
          correct: "Amazonas",
          wrong: ["Nilo", "Yangtsé", "Misisipi"]),
        q("¿Dónde nació Van Gogh?",
          correct: "Zundert, Países Bajos",
          wrong: ["Ámsterdam", "París", "Bruselas"]),
        q("¿La Muralla China está al norte o al sur?",
          correct: "Norte",
          wrong: ["Sur", "Este", "Oeste"]),
        q("¿Cómo se llama el principal río de Egipto?",
          correct: "El Nilo",
          wrong: ["El Tigris", "El Éufrates", "El Jordán"]),
        q("¿Cuál es la capital de Islandia?",
          correct: "Reykjavík",
          wrong: ["Oslo", "Helsinki", "Copenhague"]),
        q("¿En qué ciudad europea está el Atomium?",
          correct: "Bruselas",
          wrong: ["Ámsterdam", "Luxemburgo", "Berlín"]),
        q("¿A qué país pertenece la Isla de Pascua?",
          correct: "Chile",
          wrong: ["Perú", "Ecuador", "Argentina"]),
        q("¿Dónde está el David de Miguel Ángel?",
          correct: "Florencia, Italia",
          wrong: ["Roma, Italia", "Milán, Italia", "Venecia, Italia"]),
        q("¿Dónde se encuentra Santa María del Naranco?",
          correct: "Oviedo",
          wrong: ["León", "Burgos", "Santander"]),
        q("¿Dónde nació la Coca Cola?",
          correct: "Atlanta",
          wrong: ["Nueva York", "Chicago", "Boston"]),

        // Nuevas preguntas Geografía (24–48)
        q("¿Cuál es el río más caudaloso del mundo?",
          correct: "Amazonas",
          wrong: ["Nilo", "Yangtsé", "Misisipi"]),
        q("¿Cuál es el monte más alto del mundo?",
          correct: "Everest",
          wrong: ["K2", "Kangchenjunga", "Lhotse"]),
        q("¿Cuál es la lengua más hablada del mundo?",
          correct: "Chino mandarín",
          wrong: ["Inglés", "Español", "Hindi"]),
        q("¿Cómo se llama la línea vertical imaginaria desde la que se miden las longitudes?",
          correct: "Meridiano de Greenwich",
          wrong: ["Ecuador", "Trópico de Cáncer", "Trópico de Capricornio"]),
        q("¿Dónde podemos encontrar la Casa Rosada?",
          correct: "Buenos Aires",
          wrong: ["Córdoba", "Montevideo", "Santiago de Chile"]),
        q("¿Entre qué países está el Estrecho de Bering?",
          correct: "Estados Unidos y Rusia",
          wrong: ["Canadá y Rusia", "Estados Unidos y Canadá", "Rusia y Japón"]),
        q("¿Cuál es la capital de Brasil?",
          correct: "Brasilia",
          wrong: ["Río de Janeiro", "São Paulo", "Salvador"]),
        q("¿Cuál es el país de mayor tamaño del mundo?",
          correct: "Rusia",
          wrong: ["China", "Australia", "India"]),
        q("¿Cuál es la capital de Nueva Zelanda?",
          correct: "Wellington",
          wrong: ["Auckland", "Christchurch", "Hamilton"]),
        q("¿Qué cordillera separa Europa de Asia?",
          correct: "Urales",
          wrong: ["Cáucaso", "Alpes", "Cárpatos"]),
        q("¿Cómo se llama la isla donde vive la tribu no contactada menos conocida?",
          correct: "Sentinel del Norte",
          wrong: ["Sentinel del Sur", "Andamán del Norte", "Nicobar"]),
        q("¿Cuál es la capital de Filipinas?",
          correct: "Manila",
          wrong: ["Cebú", "Dávao", "Quezón"]),
        q("Además de alemán, italiano y francés, ¿qué otro idioma se habla en Suiza?",
          correct: "Romanche",
          wrong: ["Ladino", "Friulano", "Rumano"]),
        q("¿Cuál es la capital de Mongolia?",
          correct: "Ulán Bator",
          wrong: ["Astaná", "Taskent", "Biskek"]),
        q("¿De qué país europeo provienen la mayoría de familias de Argentina?",
          correct: "Italia",
          wrong: ["España", "Alemania", "Francia"]),
        q("¿En qué país se habla mayoritariamente el tagalo (tagálog)?",
          correct: "Filipinas",
          wrong: ["Malasia", "Indonesia", "Singapur"]),
        q("¿Cuál es la capital de Letonia?",
          correct: "Riga",
          wrong: ["Vilna", "Tallin", "Kaunas"]),
        q("¿Cuál es la ciudad más poblada de África?",
          correct: "El Cairo",
          wrong: ["Lagos", "Kinshasa", "Johannesburgo"]),
        q("¿Cómo se llama el plato de puchero típico de Hungría?",
          correct: "Gulash",
          wrong: ["Paprikás", "Pörkölt", "Lángos"]),
        q("¿Qué idioma de Europa continental es oficial en Sudáfrica?",
          correct: "Afrikáans",
          wrong: ["Neerlandés", "Alemán", "Inglés"]),
        q("¿Qué grupo étnico habla del 'Tiempo del Sueño' en su mitología?",
          correct: "Aborígenes australianos",
          wrong: ["Maoríes", "Inuit", "Zulúes"]),
        q("¿Cuál es la capital de Albania?",
          correct: "Tirana",
          wrong: ["Skopie", "Pristina", "Podgorica"]),
        q("¿Qué cordillera recorre el norte de Marruecos, Túnez y Argelia?",
          correct: "Atlas",
          wrong: ["Rif", "Zagros", "Aures"]),
        q("¿Cómo se llama el plato ruso de bolas de carne en masa?",
          correct: "Pelmeni",
          wrong: ["Vareniki", "Pirozhki", "Blini"]),
        q("¿Qué montaña es símbolo nacional de Armenia?",
          correct: "Ararat",
          wrong: ["Aragats", "Kazbek", "Elbrus"]),
    ]

    // MARK: - Arte y Literatura (1)
    private static let artAndLiterature: [Question] = [
        q("¿Quién pintó la Mona Lisa?",
          correct: "Leonardo da Vinci",
          wrong: ["Miguel Ángel", "Rafael", "Botticelli"]),
        q("¿Quién pintó Las Meninas?",
          correct: "Velázquez",
          wrong: ["Goya", "El Greco", "Murillo"]),
        q("¿Quién escribió 'Cumbres borrascosas'?",
          correct: "Emily Brontë",
          wrong: ["Charlotte Brontë", "Jane Austen", "Mary Shelley"]),
        q("¿El título del primer libro de Jane Austen?",
          correct: "Sentido y sensibilidad",
          wrong: ["Orgullo y prejuicio", "Emma", "Persuasión"]),
        q("‘La Luna vino a la fragua’. Así arranca un poema de…",
          correct: "Federico García Lorca",
          wrong: ["Antonio Machado", "Rafael Alberti", "Miguel Hernández"]),
        q("¿Dónde se firmó la Constitución española de 1812?",
          correct: "Cádiz",
          wrong: ["Madrid", "Sevilla", "Barcelona"]),
        q("¿Dónde se encuentran Las Meninas?",
          correct: "Museo del Prado",
          wrong: ["Museo Reina Sofía", "Louvre", "Museo Thyssen"]),
        q("¿De qué país es la autora de ‘365 DNI’?",
          correct: "Polonia",
          wrong: ["Rusia", "Rumanía", "Ucrania"]),
        q("¿Dónde nació Cervantes?",
          correct: "Alcalá de Henares",
          wrong: ["Toledo", "Valladolid", "Madrid"]),
        q("¿En qué año nació Salvador Dalí?",
          correct: "1904",
          wrong: ["1899", "1901", "1906"]),

        // Nuevas preguntas Arte y Literatura (72–96)
        q("¿Quién escribió la Ilíada y la Odisea?",
          correct: "Homero",
          wrong: ["Virgilio", "Hesíodo", "Esquilo"]),
        q("¿Qué novela escribió Miguel de Cervantes considerada cumbre de la literatura?",
          correct: "Don Quijote de la Mancha",
          wrong: ["La Celestina", "La Regenta", "El Lazarillo de Tormes"]),
        q("¿Quién pintó la Capilla Sixtina?",
          correct: "Miguel Ángel",
          wrong: ["Rafael", "Leonardo da Vinci", "Botticelli"]),
        q("¿Quién pintó el Guernica?",
          correct: "Pablo Picasso",
          wrong: ["Salvador Dalí", "Joan Miró", "Juan Gris"]),
        q("¿De qué estilo es la catedral de Notre Dame?",
          correct: "Gótico",
          wrong: ["Románico", "Barroco", "Renacentista"]),
        q("¿En qué obra aparece el soliloquio “Ser o no ser”?",
          correct: "Hamlet",
          wrong: ["Macbeth", "Otelo", "Romeo y Julieta"]),
        q("¿Quién escribió La colmena?",
          correct: "Camilo José Cela",
          wrong: ["Miguel Delibes", "Pío Baroja", "Cela Trulock"]),
        q("¿Cómo se llamaba el caballo de Don Quijote?",
          correct: "Rocinante",
          wrong: ["Babieca", "Clavileño", "Bucéfalo"]),
        q("¿En qué país fue gigante Gulliver?",
          correct: "Liliput",
          wrong: ["Brobdingnag", "Laputa", "Houyhnhnms"]),
        q("¿De qué país procede el haiku?",
          correct: "Japón",
          wrong: ["China", "Corea", "Vietnam"]),
        q("¿Quién fue apodado “el manco de Lepanto”?",
          correct: "Miguel de Cervantes",
          wrong: ["Lope de Vega", "Quevedo", "Góngora"]),
        q("¿Qué animal mitológico titula la obra política de Hobbes?",
          correct: "Leviatán",
          wrong: ["Hidra", "Quimera", "Basilisco"]),
        q("¿Quién escribió “Más allá de la libertad y la dignidad”?",
          correct: "B. F. Skinner",
          wrong: ["Carl Rogers", "Abraham Maslow", "John Watson"]),
        q("¿En qué libro se basa Blade Runner?",
          correct: "¿Sueñan los androides con ovejas eléctricas?",
          wrong: ["Ubik", "El hombre en el castillo", "Fluyan mis lágrimas, dijo el policía"]),
        q("¿Quién pintó “El grito”?",
          correct: "Edvard Munch",
          wrong: ["Gustav Klimt", "Kandinsky", "Schiele"]),
        q("¿Cómo se llama el balrog que lucha con Gandalf?",
          correct: "El Daño de Durin",
          wrong: ["Gothmog", "Ancalagon", "Glaurung"]),
        q("Además de castellano, ¿en qué idioma escribió Rosalía de Castro?",
          correct: "Gallego",
          wrong: ["Catalán", "Euskera", "Asturiano"]),
        q("¿Quién escribió La conjura de los necios?",
          correct: "John Kennedy Toole",
          wrong: ["Joseph Heller", "Kurt Vonnegut", "Truman Capote"]),
        q("¿En qué continente nació Arya Stark?",
          correct: "Westeros",
          wrong: ["Essos", "Sothoryos", "Ulthos"]),
        q("¿Quién tenía una rata llamada Scabbers?",
          correct: "Ron Weasley",
          wrong: ["Harry Potter", "Hermione Granger", "Neville Longbottom"]),
        q("¿Qué película muda de 1927 dirigió Fritz Lang?",
          correct: "Metrópolis",
          wrong: ["M, el vampiro de Düsseldorf", "Nosferatu", "El gabinete del doctor Caligari"]),
        q("¿De quién estaba enamorado el Quijote?",
          correct: "Dulcinea",
          wrong: ["Teresa Panza", "Altisidora", "Marcela"]),
        q("¿Quién pintó “La joven de la perla”?",
          correct: "Johannes Vermeer",
          wrong: ["Rembrandt", "Frans Hals", "Jan Steen"]),
        q("¿Qué pianista y cantante grabó “Glad Rag Doll”?",
          correct: "Diana Krall",
          wrong: ["Norah Jones", "Jamie Cullum", "Madeleine Peyroux"]),
        q("¿Qué poetisa escribió “Oda a Afrodita”?",
          correct: "Safo de Mitilene",
          wrong: ["Corina", "Anacreonte", "Sapho de Lesbos"]),
    ]

    // MARK: - Historia (2)
    private static let history: [Question] = [
        q("¿Quién mató a John F. Kennedy?",
          correct: "Lee Harvey Oswald",
          wrong: ["Jack Ruby", "Lyndon B. Johnson", "Richard Nixon"]),
        q("¿En qué año se produjo la caída del Muro de Berlín?",
          correct: "1989",
          wrong: ["1990", "1985", "1991"]),
        q("¿Dónde viven los presidentes de EE.UU.?",
          correct: "En la Casa Blanca",
          wrong: ["En el Capitolio", "En el Pentágono", "En Camp David"]),
        q("¿Cómo se llama la presidenta de la Comisión Europea?",
          correct: "Úrsula von der Leyen",
          wrong: ["Roberta Metsola", "Christine Lagarde", "Angela Merkel"]),
        q("¿Dónde se coronó Isabel II?",
          correct: "En la Abadía de Westminster",
          wrong: ["En el Palacio de Buckingham", "En Windsor", "En St. Paul"]),
        q("¿Cómo murió María Antonieta?",
          correct: "Decapitada",
          wrong: ["Envenenada", "Fusilada", "En el exilio"]),
        q("¿En qué año se firmó el Tratado de Versalles?",
          correct: "1919",
          wrong: ["1918", "1920", "1921"]),
        q("¿Quién fundó Roma?",
          correct: "Rómulo y Remo",
          wrong: ["Julio César", "Numa Pompilio", "Rómulo"]),
        q("¿Quién fue el primer presidente de EE.UU?",
          correct: "George Washington",
          wrong: ["Thomas Jefferson", "John Adams", "James Madison"]),
        q("¿Quién fue el primer hombre en pisar la luna?",
          correct: "Neil Armstrong",
          wrong: ["Buzz Aldrin", "Michael Collins", "Yuri Gagarin"]),
        q("¿Cuál es el nombre de la famosa batalla donde Napoleón fue derrotado?",
          correct: "Waterloo",
          wrong: ["Austerlitz", "Trafalgar", "Borodinó"]),
        q("¿Qué emperador romano legalizó el cristianismo?",
          correct: "Constantino",
          wrong: ["Nerón", "Trajano", "Marco Aurelio"]),

        // Nuevas preguntas Historia (1–23)
        q("¿Quién fue el primer presidente de la democracia española tras el franquismo?",
          correct: "Adolfo Suárez",
          wrong: ["Felipe González", "Leopoldo Calvo-Sotelo", "Santiago Carrillo"]),
        q("¿Qué fortaleza tomada por los revolucionarios marca el inicio de la Revolución Francesa?",
          correct: "La Bastilla",
          wrong: ["Los Inválidos", "Las Tullerías", "Versalles"]),
        q("¿En qué año pisó el hombre la Luna por primera vez?",
          correct: "1969",
          wrong: ["1968", "1970", "1972"]),
        q("¿Qué evento desencadenó la Primera Guerra Mundial?",
          correct: "El asesinato del archiduque Francisco Fernando",
          wrong: ["La invasión de Polonia", "El hundimiento del Lusitania", "La crisis de los misiles de Cuba"]),
        q("¿Qué suceso marca el fin de la Edad Antigua y el inicio de la Edad Media?",
          correct: "La caída del Imperio romano de Occidente (476 d.C.)",
          wrong: ["La caída de Constantinopla (1453)", "El descubrimiento de América (1492)", "La Reforma protestante (1517)"]),
        q("¿Quién fue el primer presidente de Estados Unidos?",
          correct: "George Washington",
          wrong: ["John Adams", "Thomas Jefferson", "Benjamin Franklin"]),
        q("¿Cuánto duró la Guerra de los Cien Años?",
          correct: "116 años",
          wrong: ["100 años", "99 años", "120 años"]),
        q("¿En qué año se creó la ONU?",
          correct: "1945",
          wrong: ["1942", "1948", "1950"]),
        q("¿Qué carabela no regresó del primer viaje de Colón a América?",
          correct: "La Santa María",
          wrong: ["La Pinta", "La Niña", "La Victoria"]),
        q("¿Cuál es la narración épica más antigua conservada?",
          correct: "La Epopeya de Gilgamesh",
          wrong: ["La Ilíada", "El Mahabharata", "Beowulf"]),
        q("¿Qué filósofo español desarrolló la teoría del cierre categorial?",
          correct: "Gustavo Bueno",
          wrong: ["José Ortega y Gasset", "Xavier Zubiri", "Julián Marías"]),
        q("¿Qué apellidos tenían los exploradores que dieron la primera vuelta al mundo?",
          correct: "Magallanes y Elcano",
          wrong: ["Colón y Pizarro", "Cook y Drake", "Amundsen y Scott"]),
        q("¿Qué faraón impulsó el culto monoteísta al dios Atón?",
          correct: "Akenatón (Amenhotep IV)",
          wrong: ["Tutankamón", "Ramsés II", "Esfinge de Guiza"]),
        q("¿Qué emperador romano intentó someterse a operaciones de cambio de sexo?",
          correct: "Heliogábalo",
          wrong: ["Nerón", "Calígula", "Cómodo"]),
        q("¿Quién defendió que el principio de todas las cosas es el agua?",
          correct: "Tales de Mileto",
          wrong: ["Anaxímenes", "Heráclito", "Empédocles"]),
        q("¿En qué idioma están los manuscritos más antiguos del Nuevo Testamento?",
          correct: "Griego koiné",
          wrong: ["Latín", "Arameo", "Hebreo bíblico"]),
        q("¿Quién era el primer ministro británico durante la hambruna de Bengala?",
          correct: "Winston Churchill",
          wrong: ["Neville Chamberlain", "Clement Attlee", "Stanley Baldwin"]),
        q("¿A qué isla fue confinado Napoleón tras Waterloo?",
          correct: "Santa Elena",
          wrong: ["Elba", "Córcega", "Malta"]),
        q("¿Qué filósofo danés es precursor del existencialismo?",
          correct: "Søren Kierkegaard",
          wrong: ["Friedrich Nietzsche", "Martin Heidegger", "Jean-Paul Sartre"]),
        q("¿Quiénes fueron los legendarios fundadores de Roma?",
          correct: "Rómulo y Remo",
          wrong: ["Julio César y Augusto", "Eneas y Ascanio", "Rómulo"]),
        q("¿Quién fundó el Movimiento de los Santos de los Últimos Días?",
          correct: "Joseph Smith",
          wrong: ["Brigham Young", "Charles Taze Russell", "Ellen G. White"]),
        q("¿Qué líder zulú usó la táctica de 'cuernos de búfalo'?",
          correct: "Shaka Zulú",
          wrong: ["Cetshwayo", "Menelik II", "Mansa Musa"]),
        q("¿Para qué religión es figura clave Haile Selassie I?",
          correct: "Rastafari",
          wrong: ["Cristianismo copto", "Iglesia ortodoxa etíope", "Islam"]),
    ]

    // MARK: - Entretenimiento (3) (cine, TV y famosos)
    private static let entertainment: [Question] = [
        q("¿Cuál es el nombre de la actriz Jedet?",
          correct: "Carmen",
          wrong: ["María", "Julia", "Sara"]),
        q("¿A quién interpretaba Anne Hathaway en ‘Los Miserables’?",
          correct: "Fantine",
          wrong: ["Cosette", "Éponine", "Madame Thénardier"]),
        q("¿Quién da vida a Emily en ‘Emily in Paris’?",
          correct: "Lily Collins",
          wrong: ["Lily James", "Emma Roberts", "Emma Watson"]),
        q("¿Cuál de estos actores es escocés?",
          correct: "James McAvoy",
          wrong: ["Jamie Dornan", "Michael Sheen", "Daniel Craig"]),
        q("¿Quién da vida a Anthony Bridgerton en ‘Los Bridgerton’?",
          correct: "Jonathan Bailey",
          wrong: ["Regé-Jean Page", "Luke Thompson", "Luke Newton"]),
        q("¿En qué año se estrenó ‘Stranger Things’?",
          correct: "2016",
          wrong: ["2015", "2017", "2018"]),
        q("¿Cuántos capítulos tiene ‘Breaking Bad’?",
          correct: "62",
          wrong: ["60", "64", "58"]),
        q("¿Quién interpretó a Miércoles Addams en la peli de los 90?",
          correct: "Christina Ricci",
          wrong: ["Winona Ryder", "Christen Milioti", "Anna Chlumsky"]),
        q("¿Quién es la persona más seguida en Instagram?",
          correct: "Cristiano Ronaldo",
          wrong: ["Selena Gomez", "Lionel Messi", "Kylie Jenner"]),
        q("¿Cómo se llama la novia de Piqué?",
          correct: "Clara Chía",
          wrong: ["Antonella Roccuzzo", "Georgina Rodríguez", "Aitana"]),
        q("¿Con qué político se relacionó a Marilyn Monroe?",
          correct: "John F. Kennedy",
          wrong: ["Robert Kennedy", "Richard Nixon", "Lyndon B. Johnson"]),
        q("¿Dónde nació la cantante Aitana?",
          correct: "Barcelona",
          wrong: ["Madrid", "Valencia", "Sevilla"]),

        // Nuevas preguntas Entretenimiento (49–71)
        q("¿A quién interpretaba John Travolta en “Grease”?",
          correct: "Danny Zuko",
          wrong: ["Kenickie", "Doody", "Sonny"]),
        q("¿Qué cómico imitó a Hitler en “El gran dictador”?",
          correct: "Charles Chaplin",
          wrong: ["Buster Keaton", "Harold Lloyd", "Peter Sellers"]),
        q("¿Quién dirigió y protagonizó “Ciudadano Kane”?",
          correct: "Orson Welles",
          wrong: ["Howard Hawks", "Billy Wilder", "John Huston"]),
        q("¿Quién fue el cantante de Queen?",
          correct: "Freddie Mercury",
          wrong: ["Brian May", "Roger Taylor", "John Deacon"]),
        q("¿Cómo se llama la ciudad del Mago de Oz?",
          correct: "Ciudad Esmeralda",
          wrong: ["Kansas", "Ozma", "Munchkinland"]),
        q("¿Cuáles fueron los tres primeros “payasos de la tele”?",
          correct: "Gaby, Fofó y Miliki",
          wrong: ["Gaby, Miliki y Rody", "Fofó, Miliki y Milikito", "Gaby, Fofó y Rody"]),
        q("¿De qué grupo es “Smells Like a Teen Spirit”?",
          correct: "Nirvana",
          wrong: ["Pearl Jam", "Foo Fighters", "Soundgarden"]),
        q("¿A qué banda pertenece “Master of Puppets”?",
          correct: "Metallica",
          wrong: ["Megadeth", "Slayer", "Anthrax"]),
        q("¿Qué película de Cameron fue superventas en los 90?",
          correct: "Titanic",
          wrong: ["Terminator 2", "True Lies", "Abyss"]),
        q("¿Qué película de Nolan trata de amnesia anterógrada?",
          correct: "Memento",
          wrong: ["Insomnia", "Following", "El truco final"]),
        q("¿Cómo se llama el protagonista de The Legend of Zelda?",
          correct: "Link",
          wrong: ["Zelda", "Ganon", "Sheik"]),
        q("¿Quién es el protagonista de The Sandman?",
          correct: "Morfeo",
          wrong: ["Muerte", "Destino", "Delirio"]),
        q("¿Qué banda usó el nombre “Los Estereotipos” al inicio?",
          correct: "Soda Stereo",
          wrong: ["Los Fabulosos Cadillacs", "Héroes del Silencio", "Enanitos Verdes"]),
        q("¿Quién guionizó la novela gráfica “Watchmen”?",
          correct: "Alan Moore",
          wrong: ["Frank Miller", "Neil Gaiman", "Grant Morrison"]),
        q("¿A qué saga pertenece Jack Sparrow?",
          correct: "Piratas del Caribe",
          wrong: ["Indiana Jones", "Piratas", "Los Goonies"]),
        q("¿Qué dúo hizo la BSO de “Tron: Legacy”?",
          correct: "Daft Punk",
          wrong: ["The Chemical Brothers", "Justice", "M83"]),
        q("¿Cómo se llama el protagonista de “Cowboy Bebop”?",
          correct: "Spike Spiegel",
          wrong: ["Jet Black", "Vicious", "Edward"]),
        q("¿Cómo se llama el antagonista principal de “El Rey León”?",
          correct: "Scar",
          wrong: ["Shenzi", "Zazu", "Mufasa"]),
        q("¿Quién guionizó “The Office” (versión británica)?",
          correct: "Ricky Gervais",
          wrong: ["Stephen Merchant", "Greg Daniels", "Armando Iannucci"]),
        q("¿En qué país transcurre “Chappie”?",
          correct: "Sudáfrica",
          wrong: ["Estados Unidos", "Reino Unido", "Australia"]),
        q("¿Qué youtuber hispano protagoniza “Virtual Hero”?",
          correct: "El Rubius",
          wrong: ["Willyrex", "Vegetta777", "AuronPlay"]),
        q("¿Cómo se llama el manga de Kentaro Miura protagonizado por Guts?",
          correct: "Berserk",
          wrong: ["Vagabond", "Claymore", "Vinland Saga"]),
        q("¿Cómo se llama la práctica viral de tumbarse rígido boca abajo?",
          correct: "Planking",
          wrong: ["Tebowing", "Owling", "Batmanning"]),
        q("¿Primer Donkey Kong con 3D real?",
          correct: "Donkey Kong 64",
          wrong: ["Donkey Kong Country", "DKC 2", "DKC 3"]),
        q("¿Cómo se llama el líder de los Autobots?",
          correct: "Optimus Prime",
          wrong: ["Bumblebee", "Megatron", "Ultra Magnus"]),
        q("¿Qué serie de Netflix tiene al “Demogorgon”?",
          correct: "Stranger Things",
          wrong: ["The Witcher", "Dark", "Black Mirror"]),
    ]

    // MARK: - Ciencia y Naturaleza (4)
    private static let scienceAndNature: [Question] = [
        q("¿Cuántos huesos tiene el ser humano?",
          correct: "206",
          wrong: ["210", "200", "208"]),
        q("¿Cuál es el músculo más fuerte (relativo) del cuerpo humano?",
          correct: "El masetero",
          wrong: ["El cuádriceps", "El glúteo mayor", "El tríceps"]),
        q("¿Cuál es el órgano más grande del cuerpo humano?",
          correct: "La piel",
          wrong: ["El hígado", "Los pulmones", "El intestino delgado"]),
        q("¿Cuál es el animal más grande del mundo?",
          correct: "La ballena azul",
          wrong: ["La ballena jorobada", "El calamar gigante", "La orca"]),
        q("¿Cuál es el único mamífero capaz de volar?",
          correct: "El murciélago",
          wrong: ["La ardilla voladora", "El colugo", "El planeador del azúcar"]),
        q("¿Cuántos corazones tiene un pulpo?",
          correct: "Tres",
          wrong: ["Dos", "Uno", "Cuatro"]),
        q("¿Qué gas de la atmósfera nos protege de la radiación ultravioleta?",
          correct: "El ozono",
          wrong: ["El oxígeno", "El dióxido de carbono", "El nitrógeno"]),
        q("¿Qué pigmento da color a nuestra piel?",
          correct: "La melanina",
          wrong: ["La hemoglobina", "La clorofila", "La queratina"]),
        q("¿Por qué moléculas está formada el agua?",
          correct: "Dos de hidrógeno y una de oxígeno",
          wrong: ["Una de hidrógeno y dos de oxígeno", "Dos de oxígeno y una de hidrógeno", "Hidrógeno y nitrógeno"]),
        q("¿Qué pigmento permite a las plantas hacer la fotosíntesis?",
          correct: "La clorofila",
          wrong: ["La melanina", "La hemoglobina", "La xantofila"]),
        q("¿Qué planeta es el que se encuentra más cercano al Sol?",
          correct: "Mercurio",
          wrong: ["Venus", "Marte", "Tierra"]),
        q("¿Qué es más grande, un átomo o una célula?",
          correct: "Una célula",
          wrong: ["Un átomo", "Son del mismo tamaño", "Depende del elemento"]),

        // Nuevas preguntas Ciencia y Naturaleza (97–125)
        q("¿A qué velocidad viaja la luz en el vacío (aprox.)?",
          correct: "300.000.000 km/s",
          wrong: ["3.000.000 km/s", "30.000 km/s", "300.000 km/s"]),
        q("¿Qué gas nos protege de la radiación ultravioleta del Sol?",
          correct: "Ozono",
          wrong: ["Oxígeno", "Nitrógeno", "Argón"]),
        q("¿Cómo se llama el miedo a las alturas?",
          correct: "Acrofobia",
          wrong: ["Agorafobia", "Claustrofobia", "Aerofobia"]),
        q("¿En qué teoría aparece la fórmula E=mc²?",
          correct: "Relatividad especial",
          wrong: ["Relatividad general", "Cuántica de campos", "Termodinámica"]),
        q("¿Cuál es el ave de mayor envergadura viva?",
          correct: "Albatros",
          wrong: ["Cóndor andino", "Águila harpía", "Pelícano común"]),
        q("¿Cuál es la clasificación correcta en cinco reinos?",
          correct: "Monera, Protoctista, Fungi, Vegetal, Animal",
          wrong: ["Bacterias, Protistas, Plantas, Animales, Virus",
                  "Monera, Protistas, Plantas, Animales, Arqueas",
                  "Protozoos, Hongos, Plantas, Animales, Virus"]),
        q("¿Cuál es la célula principal del sistema nervioso?",
          correct: "Neurona",
          wrong: ["Glóbulo rojo", "Miocito", "Hepatocito"]),
        q("¿Por qué fue célebre Marie Curie?",
          correct: "Descubrió la radiactividad",
          wrong: ["Descubrió la penicilina", "Descubrió los rayos X", "Descubrió el ADN"]),
        q("¿Qué ave rapaz se alimenta de huesos?",
          correct: "Quebrantahuesos",
          wrong: ["Águila real", "Buitre leonado", "Azor"]),
        q("¿Qué anfibio regenera extremidades con facilidad?",
          correct: "Ajolote",
          wrong: ["Salamandra común", "Tritón alpino", "Rana toro"]),
        q("¿Qué árbol es considerado ‘fósil viviente’?",
          correct: "Ginkgo biloba",
          wrong: ["Secuoya", "Olivo", "Baobab"]),
        q("¿Cuáles son las bases nitrogenadas del ADN?",
          correct: "Adenina, timina, guanina y citosina",
          wrong: ["Adenina, uracilo, guanina y citosina", "Adenina, timina, uracilo y citosina", "Xantina, hipoxantina, timina y citosina"]),
        q("¿Alrededor de qué planeta orbitan Ganímedes, Calisto, Ío y Europa?",
          correct: "Júpiter",
          wrong: ["Saturno", "Urano", "Neptuno"]),
        q("¿En qué archipiélago vive el cormorán que no vuela?",
          correct: "Islas Galápagos",
          wrong: ["Islas Canarias", "Islas Hawái", "Islas Azores"]),
        q("¿Cómo se llama la línea de Alnitak, Alnilam y Mintaka?",
          correct: "Cinturón de Orión",
          wrong: ["Tríangulo de Verano", "Carro Mayor", "Cruz del Sur"]),
        q("¿De qué planta se elabora el tequila?",
          correct: "Agave",
          wrong: ["Maguey azul", "Yuca", "Sábila"]),
        q("¿Cuál es el tipo de célula nerviosa más abundante en el cerebro?",
          correct: "Células gliales",
          wrong: ["Neuronas piramidales", "Astrocitos neuronales", "Microtúbulos"]),
        q("¿Quién desarrolló una teoría de la evolución paralela a Darwin?",
          correct: "Alfred Russel Wallace",
          wrong: ["Jean-Baptiste Lamarck", "Thomas H. Huxley", "Ernst Haeckel"]),
        q("¿Cómo se llama la transcripción del chino mandarín al alfabeto latino?",
          correct: "Pinyin",
          wrong: ["Wade-Giles", "Hanyu", "Zhuyin"]),
        q("¿Qué período va entre el Devónico y el Pérmico?",
          correct: "Carbonífero",
          wrong: ["Silúrico", "Triásico", "Cámbrico"]),
    ]

    // MARK: - Deportes (5)
    private static let sports: [Question] = [
        q("¿Quién dirige la selección española de fútbol?",
          correct: "Luis de la Fuente",
          wrong: ["Luis Enrique", "Vicente del Bosque", "Julen Lopetegui"]),
        q("¿Cuántas medallas olímpicas ganó Ana Peleteiro en Tokyo 2020?",
          correct: "Una de bronce",
          wrong: ["Una de plata", "Dos de bronce", "Una de oro"]),
        q("¿Qué número llevaba Benzema en el Real Madrid?",
          correct: "9",
          wrong: ["10", "7", "11"]),
        q("¿Qué deporte practicaba Simone Biles?",
          correct: "Gimnasia",
          wrong: ["Natación", "Atletismo", "Patinaje artístico"]),
        q("¿En qué año fueron los Juegos Olímpicos de Londres?",
          correct: "2012",
          wrong: ["2008", "2016", "2004"]),
        q("¿Quién ganó la liga española de fútbol en 2022?",
          correct: "Real Madrid",
          wrong: ["Barcelona", "Atlético de Madrid", "Sevilla"]),
        q("¿Cómo murió Kobe Bryant?",
          correct: "Accidente de helicóptero",
          wrong: ["Accidente de coche", "Enfermedad", "Ahogamiento"]),
        q("¿Qué selección ha ganado más Copas Mundiales de Fútbol?",
          correct: "Brasil",
          wrong: ["Alemania", "Italia", "Argentina"]),
        q("¿Quién es el atleta con más medallas olímpicas?",
          correct: "Michael Phelps",
          wrong: ["Usain Bolt", "Carl Lewis", "Mark Spitz"]),
        q("¿Cuál es el equipo de la NBA con más títulos?",
          correct: "Boston Celtics",
          wrong: ["Los Angeles Lakers", "Chicago Bulls", "San Antonio Spurs"]),

        // Nuevas preguntas Deportes y Pasatiempos (126–160)
        q("¿Cuándo se celebró la primera Copa Mundial de Fútbol?",
          correct: "1930",
          wrong: ["1928", "1934", "1938"]),
        q("¿Quién fue campeón mundial de ajedrez 1972–1974?",
          correct: "Bobby Fischer",
          wrong: ["Boris Spassky", "Anatoli Karpov", "Garry Kasparov"]),
        q("¿Quién es considerado el mejor jugador de baloncesto de la historia?",
          correct: "Michael Jordan",
          wrong: ["LeBron James", "Kobe Bryant", "Magic Johnson"]),
        q("¿Quién fue la primera mujer en ganar una medalla olímpica moderna?",
          correct: "Charlotte Cooper",
          wrong: ["Hélène de Pourtalès", "Nadia Comăneci", "Fanny Blankers-Koen"]),
        q("¿Quién tiene el récord de 100 metros lisos?",
          correct: "Usain Bolt",
          wrong: ["Tyson Gay", "Yohan Blake", "Asafa Powell"]),
        q("¿Cada cuántos años se celebran los Juegos Olímpicos de verano?",
          correct: "Cada cuatro años",
          wrong: ["Cada dos años", "Cada cinco años", "Cada seis años"]),
        q("¿Qué selección ha ganado más Mundiales de fútbol?",
          correct: "Brasil",
          wrong: ["Alemania", "Italia", "Argentina"]),
        q("¿Quién fue Cobi?",
          correct: "La mascota de Barcelona 1992",
          wrong: ["Mascota de Seúl 1988", "Mascota de Atlanta 1996", "Mascota de Sídney 2000"]),
        q("¿Qué ajedrecista cubano fue campeón mundial entre 1921 y 1927?",
          correct: "José Raúl Capablanca",
          wrong: ["Emanuel Lasker", "Alekhine", "Mijaíl Botvínik"]),
        q("¿En qué ciudad está el estadio de Mestalla?",
          correct: "Valencia",
          wrong: ["Sevilla", "Madrid", "Bilbao"]),
        q("¿Qué tenista nacida en 1956 ganó 18 Grand Slam?",
          correct: "Martina Navrátilová",
          wrong: ["Chris Evert", "Steffi Graf", "Billie Jean King"]),
        q("¿Cuál es el deporte más popular en la India?",
          correct: "Críquet",
          wrong: ["Fútbol", "Hockey sobre hierba", "Bádminton"]),
        q("¿Dónde nació Lionel Messi?",
          correct: "Rosario",
          wrong: ["Buenos Aires", "Córdoba", "La Plata"]),
        q("¿Cómo se apodó al esquiador Michael Thomas Edwards?",
          correct: "Eddie el Águila",
          wrong: ["El Halcón", "El Cohete", "El Tigre"]),
        q("¿Qué golfista tiene más majors ganados?",
          correct: "Jack Nicklaus",
          wrong: ["Tiger Woods", "Arnold Palmer", "Ben Hogan"]),
        q("¿Cómo se conoce a Jason Zimmerman en Super Smash Bros.?",
          correct: "Mew2King (M2K)",
          wrong: ["Hungrybox", "Armada", "Leffen"]),
        q("¿Qué arte marcial sudamericana parece un baile?",
          correct: "Capoeira",
          wrong: ["Sambo", "Jiu-jitsu", "Savate"]),
        q("¿Qué futbolista originó la “gravesinha”?",
          correct: "Thomas Gravesen",
          wrong: ["Zinedine Zidane", "Ronaldinho", "Juan Román Riquelme"]),
        q("¿Qué nadador ganó 4 oros y 2 platas en Londres 2012?",
          correct: "Michael Phelps",
          wrong: ["Ryan Lochte", "Ian Thorpe", "Sun Yang"]),
        q("¿Dónde nació Valentino Rossi?",
          correct: "Urbino",
          wrong: ["Tavullia", "Roma", "Bolonia"]),
        q("¿Qué videojuego de estrategia es masivo en Corea del Sur?",
          correct: "StarCraft",
          wrong: ["Warcraft III", "Age of Empires II", "Command & Conquer"]),
        q("¿Qué español ganó las Series Mundiales de Ultra Running 2012–2014?",
          correct: "Kilian Jornet",
          wrong: ["Luis Alberto Hernando", "Pau Capell", "Zaid Ait Malek"]),
        q("¿Qué arte marcial es el “boxeo tailandés”?",
          correct: "Muay thai",
          wrong: ["Karate", "Kickboxing", "Taekwondo"]),
        q("¿En qué equipo jugaba David Beckham en 2007?",
          correct: "LA Galaxy",
          wrong: ["Real Madrid", "AC Milan", "Manchester United"]),
        q("¿Qué jugador de la NBA ha ganado más campeonatos?",
          correct: "Bill Russell",
          wrong: ["Michael Jordan", "Kareem Abdul-Jabbar", "Sam Jones"]),
        q("¿Qué piloto español de MotoGP tiene más títulos?",
          correct: "Marc Márquez",
          wrong: ["Jorge Lorenzo", "Álex Crivillé", "Dani Pedrosa"]),
        q("¿Qué piloto español ganó el Mundial de F1?",
          correct: "Fernando Alonso",
          wrong: ["Carlos Sainz", "Pedro de la Rosa", "Alfonso de Portago"]),
        q("¿En qué franquicia NBA jugó toda su carrera Kobe Bryant?",
          correct: "Los Angeles Lakers",
          wrong: ["Los Angeles Clippers", "Chicago Bulls", "Boston Celtics"]),
        q("¿Quién ha ganado más veces Roland Garros?",
          correct: "Rafael Nadal",
          wrong: ["Björn Borg", "Novak Djokovic", "Roger Federer"]),
        q("¿Qué portero del Barça probó suerte en Barcelona Dragons?",
          correct: "Jesús Angoy",
          wrong: ["Víctor Valdés", "José Manuel Pinto", "Andoni Zubizarreta"]),
        q("¿Cómo se llamaba Cassius Clay tras convertirse al islam?",
          correct: "Muhammad Ali",
          wrong: ["Malcolm X", "Kareem Abdul-Jabbar", "Mike Tyson"]),
        q("¿Quién es el jugador más alto que ha jugado en la ACB?",
          correct: "Christ Koumadje",
          wrong: ["Walter Tavares", "Ralph Sampson", "Robert Parish"]),
        q("¿Qué periodista popularizó la expresión “Jugón”?",
          correct: "Andrés Montes",
          wrong: ["Manolo Lama", "José Ramón de la Morena", "Paco González"]),
        q("¿Qué futbolista argentino fue apodado “El Conejito”?",
          correct: "Javier Saviola",
          wrong: ["Javier Pastore", "Javier Zanetti", "Pablo Aimar"]),
        q("¿Qué entrenador español logró el primer sextete?",
          correct: "Pep Guardiola (2008–2009)",
          wrong: ["Luis Enrique", "Vicente del Bosque", "Unai Emery"]),
    ]

    // MARK: - Utilidades

    // Crea una Question con 4 opciones y las baraja
    private static func q(_ text: String, correct: String, wrong: [String]) -> Question {
        let options = [AnswerOption(text: correct, isCorrect: true)] +
                      wrong.prefix(3).map { AnswerOption(text: $0, isCorrect: false) }
        return Question(text: text, options: options.shuffled())
    }
}
